Instance Store
PitcherAG/pitcher-vue-sdk pull request #146
Opened 2020-11-20 13:56 UTC by elibolonur

- Do not merge yet
- Docs will be updated
- Featuering new instance and serverjson store

2020-11-20 14:11 UTC, digi604 commented
looks very good... I like it. Tests fail though.

2020-11-21 11:44 UTC, elibolonur commented
Beta.13 version is corrupt at the moment as there are 2 functions that use same name on export. I've sent info to @yasatbilgin  how to solve it.

2020-11-23 11:25 UTC, digi604 requested changes

2020-11-23 11:25 UTC, digi604 commented on src/ui/serverJSONStore.js
> +
can we move locale and systemLang to i18n store?
can we add SystemStore for stuff like batteryLevel etc?
can we add FileStore for files, categories etc?

just splitting this up so we do not have 1 huge store for everything?

2020-11-23 11:27 UTC, digi604 commented
Is there any way to test at least some of the stuff? -3% coverage.... is bad

2020-11-23 15:54 UTC, digi604 commented on src/db/query.js
> -    console.log(query)
can we make that configurable with a env variable if this should print?

2020-12-09 14:19 UTC, closed without merging